# Generated by Django 4.1 on 2022-08-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('su', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sales',
            new_name='manager',
        ),
        migrations.AddField(
            model_name='user',
            name='team_lead',
            field=models.BooleanField(default=False),
        ),
    ]
